version: '3'

services:
  db:
    container_name: my-db2test
    ports:
      - 54322:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    image: postgres:latest
    restart: unless-stopped

  pgadmin:
    container_name: pg-admintest
    ports:
      - 8080:8080
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAUL_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAUL_PASSWORD}
    image: dpage/pgadmin4:latest

  myapp:
    container_name: my-apptest
    ports:
      - 1337:1337
    environment:
      - DATABASE_CLIENT=${DATABAS_CLIENT}
      - DATABASE_HOST=${DATABAS_HOST}
      - DATABASE_PORT=${DATABAS_PORT}
      - DATABASE_NAME=${DATABAS_NAME}
      - DATABASE_USERNAME=${DATABAS_USERNAME}
      - DATABASE_PASSWORD=${DATABAS_PASSWORD}
      - DATABASE_SSL=false
    image: naskio/strapi:latest
